name: CreateConfiguration
on: workflow_dispatch

jobs:
    build:
        runs-on: [self-hosted, linux, x64]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
            - name: Install modules
              run: npm ci
            - name: Create-env file
              uses: SpicyPizza/create-envfile@v2.0
              with:
                envKey_KEYVAULT_URI: ${{ secrets.keyvault_uri }}
                envKey_AZURE_TENANT_ID: ${{ secrets.azure_tenant_id}}
                envKey_AZURE_CLIENT_ID: ${{ secrets.azure_client_id}}
                envKey_AZURE_CLIENT_SECRET: ${{ secrets.azure_client_secret}}
            - name: Creating configuration
              run: npm configcreator.js
    
              
    Configuration-Deployment:
        name: Configuration-Deployment  
        runs-on: [self-hosted, linux, x64]
        needs: build
        steps:
          - name: Install SSH Key
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              if_key_exists: ignore
              known_hosts: unnecessary
          
          - name: Adding Known Hosts
            run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_DEV_HOSTS }}  >> ~/.ssh/known_hosts

          - name: Deploying Config
            run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./config.json ${{ secrets.SSH_USER }}@${{ secrets.SSH_DEV_HOSTS }}:/usr/share/nginx/html/sampleapp
